### ISSUE TITLE
懂什么叫开源？

### ISSUE THREAD

**Issue by singletoint** [zhimengzhe/iBarn#19]
怕是神经病吧，这垃圾玩意都开源了还，版权所有，翻版必究，未经同意不得用于商业项目

**Comment by TaiYouWeb** [comment]
@singletoint 
这是此作者的劳动心血，他有权提他的要求。
你这东西呢，要点B脸，谁都不欠你的，用不着在这狗叫，给我有礼貌点。

**Comment by singletoint** [comment]
@TaiYouWeb 菜鸡，心血？怕是没见过代码吧，请你继续当狗继续咬叫！太抬举自己了吧，还把自己当个东西了
